services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example-template
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]
    networks:
      - example-template-api_network

networks:
  example-template-api_network:
    external: true
